### ISSUE TITLE
Incorrect track plays

### ISSUE THREAD

**Issue by ToskinBoskin** [robinfriedli/botify#237]
Whenever there are multiple songs with the same name it plays a random one and often times is not the actual song that I want. It seems to ignore the artist name so there might be some way to fix it using that.

**Comment by robinfriedli** [comment]
I presume you're talking about Spotify to YouTube redirection? In that case see #137 and #216. Define "often", I don't think I can recall a single instance where it played a completely wrong track within the last few months but it does depend on the popularity of the artists you're listening to, although even with tracks that only have a few thousand views I haven't really noticed any serious issues since the last time I improved the algorithm back in September. What is fairly common is that a different version of the track is found (live version, different mix / cover etc.) but in my experience I'd say about 90% of results are solid.

No it does not ignore the artist, see https://github.com/robinfriedli/botify/blob/master/src/main/java/net/robinfriedli/botify/audio/youtube/YouTubeService.java#L781. In fact it tries several different combinations of applying the artists to the track name (no artists, only first artist before track name, only first artist after track name, all artists before track name, all artists after track name, fist artist before track name + remaining artists after track name) and picks the lowest levenshtein distance. It does not pick a random track, it picks the one with the highest score based on levenshtein distance, whether or not any artists appear in the channel title, the popularity and the index within the search result list.

If this really is just about searching tracks on Spotify, this doesn't really have anything to do with the bot, when entering `play foo bar`, "foo bar" is simply passed to the Spotify API as query string, see [their API documentation](https://developer.spotify.com/documentation/web-api/reference/#endpoint-search). If you want to filter by artist simply write `play foo artist:bar`. This is mentioned by the help page for the play command and any command where it applies.
